CREATE TABLE "albums" (
	"id" varchar PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"questions" jsonb NOT NULL,
	"cover_image" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "albums_title_idx" ON "albums" USING btree ("title");--> statement-breakpoint
CREATE INDEX "albums_is_active_idx" ON "albums" USING btree ("is_active");--> statement-breakpoint
INSERT INTO "albums" ("id", "title", "description", "questions", "cover_image", "is_active", "created_at", "updated_at") VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Our Family History', 'These questions help you revisit the people, places, and small moments that shaped your earliest memories — the roots of who you are today.', '["When you think of your childhood home, what picture or feeling comes to mind first?","Did your family have any small traditions or habits that made your days special?","Which dishes instantly take you back to your childhood, and who used to make them?","What was your neighborhood like when you were growing up?","Who were your childhood friends, and what games did you play together?","What was school like for you as a child?","Did you have a favorite teacher or mentor who influenced you?","What festivals or celebrations did your family observe?","What stories did your parents or grandparents tell you about their own childhoods?","What was your relationship like with your siblings or cousins?","Were there any family heirlooms or treasures that were important to your family?","What kind of music or entertainment did your family enjoy together?","Did your family face any hardships when you were young, and how did you overcome them?","What values did your parents emphasize most when raising you?","Is there a family story that has been passed down through generations?"]', 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800&q=80', true, now(), now()),
('b2c3d4e5-f6a7-8901-bcde-f23456789012', 'Their Life Paths', 'These questions invite you to reflect on your life''s journey — the moments, choices, and people that taught you who you are.', '["What was your first job, and how did you feel earning your first income?","What were your dreams when you were young, and how did they change with time?","Was there a mistake that ended up teaching you something important?","How did you meet your life partner, and what drew you to them?","What was the proudest moment of your career or work life?","Have you ever taken a risk that completely changed your life''s direction?","What was the most difficult decision you ever had to make?","Who has been your greatest source of support throughout your life?","What accomplishment are you most proud of?","If you could go back and give your younger self advice, what would it be?","What was a turning point in your life that shaped who you became?","How did you handle setbacks or failures along the way?","What traditions or practices have you carried forward from your own upbringing?","What unexpected joy or surprise has life brought you?","How has your definition of success changed over the years?"]', 'https://images.unsplash.com/photo-1516414447565-b14be0adf13e?w=800&q=80', true, now(), now()),
('c3d4e5f6-a7b8-9012-cdef-345678901234', 'Words of Wisdom', 'These questions encourage you to share the wisdom, values, and reflections that your life''s journey has taught you — the thoughts you''d like to pass on.', '["What lesson from your parents has stayed with you through life?","Have you ever experienced a complete change in your beliefs or outlook?","How have your personal or spiritual beliefs guided your path?","What do you think is the secret to a happy life?","What would you like future generations to know about living a meaningful life?","What does love mean to you, and how has that understanding evolved?","What do you consider your greatest strength, and how did you develop it?","If you could share one piece of wisdom with the world, what would it be?","What brings you the most peace and contentment in life?","How do you want to be remembered by those you love?","What role has forgiveness played in your life?","What do you think is most important when raising a family?","What advice would you give about handling difficult times?","What do you believe makes a relationship strong and lasting?","Looking back on your life, what matters most to you now?"]', 'https://images.unsplash.com/photo-1519491050282-cf00c82424b4?w=800&q=80', true, now(), now()),
('d4e5f6a7-b8c9-0123-def4-456789012345', 'Love & Relationships', 'These questions explore the bonds that matter most — the love, connections, and relationships that have shaped your heart and life.', '["How did you know you had found the right person to spend your life with?","What is the most important lesson you''ve learned about love?","How has your understanding of relationships changed over the years?","What advice would you give to someone about building lasting relationships?"]', 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=800&q=80', true, now(), now());

